services:
  mysql:
    image: mysql:8.0
    container_name: url-shortener-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: urldb
    ports:
      - "3307:3306"
    command: --default-authentication-plugin=mysql_native_password